import { UiLanguage } from '@/src/types/home';

const SECTION_TYPE_LABELS: Record<string, { en: string; th: string }> = {
  prepare: { en: 'Prepare', th: 'เตรียมตัว' },
  comprehension: { en: 'Comprehension', th: 'ความเข้าใจ' },
  transcript: { en: 'Transcript', th: 'สคริปต์บท' },
  conversation: { en: 'Conversation', th: 'บทสนทนา' },
  apply: { en: 'Apply', th: 'การนำไปใช้' },
  understand: { en: 'Understand', th: 'การทำความเข้าใจ' },
  extra_tip: { en: 'Extra Tips', th: 'เคล็ดลับเพิ่มเติม' },
  common_mistake: { en: 'Common Mistakes', th: 'ข้อผิดพลาดที่พบบ่อย' },
  phrases_verbs: { en: 'Phrases & Verbs', th: 'วลีและคำกริยา' },
  culture_note: { en: 'Culture Note', th: 'เกร็ดความรู้ทางวัฒนธรรม' },
  practice: { en: 'Practice', th: 'แบบฝึกหัด' },
};

export const getLessonSectionLabel = (language: UiLanguage, sectionType: string | null | undefined) => {
  if (!sectionType) {
    return language === 'th' ? 'บทเรียน' : 'Lesson section';
  }

  return SECTION_TYPE_LABELS[sectionType]?.[language] ?? sectionType.replace(/_/g, ' ');
};

export const getLessonSectionTitle = (
  language: UiLanguage,
  sectionType: string | null | undefined,
  index: number
) => getLessonSectionLabel(language, sectionType) || `${language === 'th' ? 'ส่วนที่' : 'Section'} ${index + 1}`;

export const getLessonDetailCopy = (language: UiLanguage) => {
  if (language === 'th') {
    return {
      missingLessonId: 'ไม่พบ lesson id',
      fetchLessonFailed: 'โหลดบทเรียนไม่สำเร็จ',
      sectionEyebrow: (index: number) => `ส่วนที่ ${index + 1}`,
      noSectionsYet: 'ยังไม่มี sections',
      backToLessonCover: 'กลับไปหน้าปกบทเรียน',
      finishLesson: 'จบบทเรียน',
      nextSection: 'ไปยังส่วนถัดไป',
      nextQuestion: 'คำถามถัดไป',
      sectionCounter: (activeIndex: number, count: number) => `${activeIndex + 1} จาก ${count} ส่วน`,
      questionCounter: (activeIndex: number, count: number) => `คำถาม ${activeIndex + 1} จาก ${count}`,
      sectionMenuLabel: 'สารบัญบทเรียน',
      startLesson: 'เริ่มบทเรียน',
      unlockLesson: 'สมัครสมาชิกเพื่อปลดล็อก',
      lockedLessonTitle: 'บทเรียนนี้ยังล็อกอยู่',
      lockedLessonBody: 'คุณยังดูหน้าปกบทเรียนนี้ได้ แต่ต้องสมัครสมาชิกก่อนจึงจะเริ่มเรียนเนื้อหาทั้งหมดได้',
      backToLibrary: 'กลับไปหน้าคลังบทเรียน',
      translateToThaiLabel: 'แปลเป็นภาษาไทย',
      translateToEnglishLabel: 'แปลเป็นภาษาอังกฤษ',
      showEnglish: 'ดูภาษาอังกฤษ',
      showThai: 'แปลเป็นภาษาไทย',
      hideBackstory: 'ซ่อนหน้าเรื่องราวเบื้องหลัง',
      showBackstory: 'ดูหน้าเรื่องราวเบื้องหลัง',
      checkAnswers: 'ตรวจสอบคำตอบ',
      audioReady: 'มีเสียง',
      noAudioYet: 'ยังไม่มีเสียง',
      noSectionYet: 'ยังไม่มี section',
      noSectionAvailable: 'ยังไม่มี section ให้แสดง',
      sectionLoadedPlaceholder:
        'เราโหลดข้อมูลของ section นี้แล้ว แต่จะยังไม่แสดง raw content หรือ content_jsonb ตรงนี้จนกว่าจะมี native renderer ที่เหมาะสม',
      tabExistsPlaceholder: 'ส่วนนี้มีข้อมูลใน resolved lesson payload แล้ว แต่ยังต้องมี renderer เฉพาะทางสำหรับแสดงผล',
      rendererNext: 'renderer ถัดไป',
      rendererReady: (label: string) => `${label} พร้อมต่อเข้ากับ native rich renderer`,
      rendererLanding: 'section renderer จะเข้ามาที่พื้นที่นี้',
      richNodesLoaded: (count: number) =>
        `โหลด rich nodes แล้วสูงสุด ${count} block สำหรับ section นี้ ตอนนี้เหลือแค่แปล block เหล่านั้นเป็น native components`,
      tabRendererMissing: (title: string) =>
        `${title} มีข้อมูลพร้อมแล้วจาก resolved lesson payload แต่ renderer แบบ native สำหรับส่วนนี้ยังไม่ได้ต่อเข้ามา`,
      richContentLanding: 'เมื่อ lesson มี sections จริงแล้ว พื้นที่นี้จะใช้แสดง rich content แบบ native',
      richBlocksLoaded: 'โหลด rich lesson blocks สำหรับ section นี้แล้ว',
      audioLinkedData: 'section นี้มีข้อมูลเสียงที่สามารถต่อเข้ากับ player ได้',
      sectionTypeLabel: (label: string) => `ชนิดของ section: ${label}`,
      lessonLabel: 'บทเรียน',
      lessonSections: 'ส่วนของบทเรียน',
      lessonFocus: 'ประเด็นหลักของบทเรียน',
      greatJob: 'ทำได้ดีมาก!',
      tryAgain: 'ลองอีกครั้ง',
      loadingImageAlt: 'กำลังโหลดบทเรียน',
      loadingLessonCta: 'กำลังเตรียมบทเรียน...',
      loadingErrorTitle: 'มีบางอย่างผิดพลาด',
      loadingErrorBody: 'เราโหลดบทเรียนนี้ไม่สำเร็จ ลองอีกครั้งอีกสักครู่นะ',
      audioTrayStatus: 'เสียงพร้อม',
      audioTrayPlaying: 'กำลังเล่น',
      audioTrayLoading: 'กำลังโหลดเสียง',
      conversationIntroEyebrow: 'ก่อนเริ่ม',
      conversationIntroBody: 'ฟังบทสนทนาเต็มก่อน แล้วคำถามในบทเรียนจะอิงจากสิ่งที่คุณได้ยิน',
      conversationIntroHint: 'กด Play เพื่อเริ่มได้เลย หากยังไม่อยากฟังตอนนี้ กดปิดแล้วใช้แถบเสียงด้านล่างภายหลังได้',
      translatingContent: 'กำลังแปล...',
      applyNote: 'ไม่ต้องกังวลว่าจะทำผิด!',
      applySubmit: 'ดูตัวอย่างคำตอบ',
      applyResponseNote: 'นี่คือตัวอย่างหนึ่งของคำตอบที่เป็นไปได้ ไม่จำเป็นต้องเหมือนกันทุกคำ',
      applyPlaceholder: 'พิมพ์คำตอบของคุณที่นี่…',
      practiceEmpty: 'ยังไม่มีแบบฝึกหัดในส่วนนี้',
      practiceChooseAnswer: 'เลือกคำตอบที่ถูกต้องที่สุด',
      practiceReset: 'เริ่มใหม่',
      practiceOpenPlaceholder: 'พิมพ์คำตอบของคุณ…',
      practiceChecking: 'กำลังตรวจ...',
      practiceAnswerAll: 'กรุณาตอบให้ครบก่อนตรวจ',
      practiceLoginRequired: 'กรุณาเข้าสู่ระบบเพื่อตรวจคำตอบ',
      practiceCorrect: 'ถูกต้อง',
      practiceNeedsWork: 'ลองแก้อีกนิด',
      phrasesIntro:
        'เราเลือกวลีสำคัญจากบทเรียนนี้มาให้ทีละใบ เพื่อให้คุณโฟกัสกับความหมาย การแปล และเสียงตัวอย่างได้ง่ายขึ้น',
      phrasesEmpty: 'ยังไม่มี phrase card ที่พร้อมแสดงใน section นี้',
      phrasesCardLabel: 'Phrase Card',
      phrasesVariantLabel: (variant: number) => `เวอร์ชัน ${variant}`,
      phrasesAudioReady: 'มีเสียงตัวอย่าง',
      phrasesAudioMissing: 'ยังไม่มีเสียงตัวอย่าง',
      phrasesBrowseAll: 'ดู phrase card ใน section นี้ให้ครบก่อน แล้วค่อยไป section ถัดไป',
      phrasesNotesLabel: 'สิ่งที่ควรสังเกต',
      phrasesPlainFallbackLabel: 'ตัวอย่างการใช้งาน',
      prepareCardTitle: 'ก่อนฟังบทสนทนา',
      prepareCardSubtitle: 'ทำความคุ้นเคยกับคำศัพท์ที่คุณจะได้ยินในบทสนทนา',
      prepareEmpty: 'ยังไม่มีรายการเตรียมตัวใน section นี้',
      completionSavedError: 'เราไม่สามารถบันทึกความคืบหน้าของบทเรียนนี้ได้ ลองอีกครั้งอีกสักครู่นะ',
      completionSuccessTitle: 'เก่งมาก!',
      completionSuccessBody: (lessonNumber: string) => `คุณเรียนจบ บทเรียน ${lessonNumber} แล้ว`,
      completionIncompleteTitle: 'Almost there!',
      completionIncompleteBody: 'ทำแบบฝึกหัดให้ครบทุกข้อและกดตรวจคำตอบของแต่ละข้อก่อน จึงจะจบบทเรียนนี้ได้',
      finishPracticesBeforeComplete: 'ทำแบบฝึกหัดให้เสร็จก่อนจึงค่อยทำเครื่องหมายว่าบทเรียนนี้เสร็จแล้ว!',
      completionReview: 'ทบทวน',
      completionKeepGoing: 'เรียนต่อ',
      completionClose: 'ปิด',
      completionOpenLibrary: 'คลังบทเรียน',
    };
  }

  return {
    missingLessonId: 'Missing lesson id.',
    fetchLessonFailed: 'Failed to load lesson.',
    sectionEyebrow: (index: number) => `Section ${index + 1}`,
    noSectionsYet: 'No sections yet',
    backToLessonCover: 'Back to lesson cover',
    finishLesson: 'Finish lesson',
    nextSection: 'Next Section',
    nextQuestion: 'Next Question',
    sectionCounter: (activeIndex: number, count: number) => `${activeIndex + 1} of ${count} sections`,
    questionCounter: (activeIndex: number, count: number) => `Question ${activeIndex + 1} of ${count}`,
    sectionMenuLabel: 'Lesson sections',
    startLesson: 'Start lesson',
    unlockLesson: 'Subscribe to unlock',
    lockedLessonTitle: 'This lesson is locked',
    lockedLessonBody: 'You can preview this lesson cover, but membership is required before you can enter the full lesson.',
    backToLibrary: 'Back to lesson library',
    translateToThaiLabel: 'Translate to Thai',
    translateToEnglishLabel: 'Translate to English',
    showEnglish: 'View English',
    showThai: 'Translate to Thai',
    hideBackstory: 'Hide backstory',
    showBackstory: 'Show backstory',
    checkAnswers: 'CHECK ANSWERS',
    audioReady: 'Audio ready',
    noAudioYet: 'No audio yet',
    noSectionYet: 'No section yet',
    noSectionAvailable: 'No lesson section is available yet',
    sectionLoadedPlaceholder:
      'This section is loaded, but we are intentionally not rendering raw content or content_jsonb here until the native renderer is ready.',
    tabExistsPlaceholder:
      'This lesson tab exists in the resolved lesson payload, but it still needs a dedicated native renderer.',
    rendererNext: 'Renderer Next',
    rendererReady: (label: string) => `${label} is ready for native rich rendering`,
    rendererLanding: 'The section renderer will land in this study area.',
    richNodesLoaded: (count: number) =>
      `The resolved payload is loaded for this section with up to ${count} rich blocks. The remaining work is translating those blocks into native components.`,
    tabRendererMissing: (title: string) =>
      `${title} is already present in the resolved lesson payload, but the native renderer for this section is not wired in yet.`,
    richContentLanding: 'As soon as the lesson exposes section data, this area will host the native rich content flow.',
    richBlocksLoaded: 'Rich lesson blocks are loaded for this section.',
    audioLinkedData: 'This section includes audio-linked data that can be wired into the player.',
    sectionTypeLabel: (label: string) => `Section type: ${label}`,
    lessonLabel: 'Lesson',
    lessonSections: 'lesson sections',
    lessonFocus: 'Lesson Focus',
    greatJob: 'GREAT JOB!',
    tryAgain: 'TRY AGAIN',
    loadingImageAlt: 'Loading lesson',
    loadingLessonCta: 'Preparing lesson...',
    loadingErrorTitle: 'Something went wrong',
    loadingErrorBody: 'We could not load this lesson just yet. Please try again in a moment.',
    audioTrayStatus: 'Audio ready',
    audioTrayPlaying: 'Now playing',
    audioTrayLoading: 'Loading audio',
    conversationIntroEyebrow: 'Before You Begin',
    conversationIntroBody: 'Listen to the full conversation first. The questions in this lesson are based on what you hear.',
    conversationIntroHint: 'Tap Play to begin. If you want to skip for now, close this screen and use the audio bar at the bottom later.',
    translatingContent: 'Translating...',
    applyNote: 'Don’t worry about making mistakes!',
    applySubmit: 'SEE AN EXAMPLE ANSWER',
    applyResponseNote: 'This is just one possible example response. Yours does not need to match it exactly.',
    applyPlaceholder: 'Type your response here…',
    practiceEmpty: 'There are no exercises in this section yet.',
    practiceChooseAnswer: 'Choose the best answer.',
    practiceReset: 'RESET',
    practiceOpenPlaceholder: 'Type your answer…',
    practiceChecking: 'CHECKING...',
    practiceAnswerAll: 'Please answer every prompt before checking.',
    practiceLoginRequired: 'Please log in to check your answers.',
    practiceCorrect: 'Correct',
    practiceNeedsWork: 'Needs another try',
    phrasesIntro:
      'This section works best one phrase card at a time so you can focus on the wording, translation, and example audio.',
    phrasesEmpty: 'There are no phrase cards ready to show in this section yet.',
    phrasesCardLabel: 'Phrase Card',
    phrasesVariantLabel: (variant: number) => `Variant ${variant}`,
    phrasesAudioReady: 'Example audio ready',
    phrasesAudioMissing: 'No example audio yet',
    phrasesBrowseAll: 'Browse all phrase cards in this section before moving to the next lesson section.',
    phrasesNotesLabel: 'What to Notice',
    phrasesPlainFallbackLabel: 'Usage Notes',
    prepareCardTitle: 'BEFORE YOU LISTEN',
    prepareCardSubtitle: "Get familiar with the words you'll hear in the conversation.",
    prepareEmpty: 'There are no preview items in this section yet.',
    completionSavedError: 'We could not save this lesson as complete just yet. Please try again in a moment.',
    completionSuccessTitle: 'Nice work!',
    completionSuccessBody: (lessonNumber: string) => `You finished Lesson ${lessonNumber}.`,
    completionIncompleteTitle: 'So close!',
    completionIncompleteBody: 'Finish every practice and tap Check Answers for each one to mark this lesson complete.',
    finishPracticesBeforeComplete: 'Finish the practices before marking the lesson complete!',
    completionReview: 'Review',
    completionKeepGoing: 'Keep going',
    completionClose: 'Close',
    completionOpenLibrary: 'Lesson Library',
  };
};
